-- migrate:up
CREATE TABLE users (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  email VARCHAR(100) NOT NULL,
  password VARBINARY(200) NOT NULL,
  birthday VARCHAR(50) NOT NULL,
  phone_number VARCHAR(50) NOT NULL,
  point DECIMAL(9,2) NOT NULL DEFAULT 1000000.00,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP
);

-- migrate:down
DROP TABLE users;